### ISSUE TITLE
Rust services fail to startup

### ISSUE THREAD

**Issue by lexer21** [maximumstock/poe-stash-indexer#373]
Hello, i have been playing around with the setup of the project, I generated my poe and new relic credentials, but when i do `make up` the  all the rust services return the following error:

```
Error: Io(Custom { kind: Uncategorized, error: "failed to lookup address information: Name or service not known" })
[Finished running. Exit status: 1]
```
Any ideas what might be the problem?

My .env.development looks like this:

```
# General env info
ENV=development
RUST_LOG=info,ureq=warn,sqlx=warn
METRICS_PORT=4000

# Reverse Proxy
HOST=localhost
HOST_PUBLIC=localhost:8888
HTPASSWD='poe:poe'

# indexer
# DATABASE_URL=postgres://poe:poe@db:5432/poe
DATABASE_URL=postgres://poe:poe@db:5432/poe
TRADE_API_DATABASE_URL=postgres://poe:poe@db:5432/poe
RABBITMQ_SINK_ENABLED=true
RABBITMQ_URL=amqp://poe:poe@rabbitmq
RABBITMQ_PRODUCER_ROUTING_KEY=stash-record-stream
POE_CLIENT_ID=...
POE_CLIENT_SECRET=...

# trade
AMQP_ADDR=amqp://poe:poe@rabbitmq

# Postgres
POSTGRES_PASSWORD=poe
POSTGRES_USER=poe
POSTGRES_DB=poe
PG_DATA=/pg-data

# RabbitMQ
RABBITMQ_USER=poe
RABBITMQ_PASSWORD=poe

# Service Communication
RABBITMQ_HOST=rabbitmq
INDEXER_HOST=indexer
TRADE_API_HOST=trade-api
TRADE_INGEST_HOST=trade-ingest

# OTEL & New Relic
OTLP_ENDPOINT=https://otlp.eu01.nr-data.net:4318
OTLP_LICENSE_KEY=...
```

otel-collector-config.yaml:

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlp:
    endpoint: https://otlp.eu01.nr-data.net:4318
    headers:
      api-key:...

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

```

Few things want to point out. I noticed that env variable TRADE_API_DATABASE_URL is referenced two times in the code but its not present in the template i assume it should be renamed to DATABASE_URL in the rust code. Also It would really helpfull to add some extra documentation for the project setup, it was not imediatly obvious that i have to copy the template, fill in the secrets and run `instantiate.sh` and how to do otlp setup.  Also why do we send otlp data in local dev enviroment to new relic? I would understand for a production setup, but for local development seems like bit overkill, would be nice to make it as an optional service for local development.

Best regards
